#!/usr/bin/env bash

version="1.1.0"
name="InventoryAdditions"

if dotnet build -c Release; then
	rm Release*.zip
	zip -j Release${version}.zip ./InventoryAdditions/bin//Release/${name}.dll

	echo "OK"
else
	echo "Build failed"
fi
